name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  tests-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest tests/test_unit.py

      - name: Run integration tests
        run: pytest tests/test_integration.py

      - name: Install Selenium
        run: pip install selenium webdriver-manager

      - name: Start Flask app
        run: |
          python app.py &
          sleep 5

      - name: Run E2E tests
        run: pytest tests/test_e2e.py

      - name: Build Docker image (test only)
        run: |
          docker build -t ktzkvin/taskmanager:ci .

  docker-push:
    needs: tests-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build production image
        run: |
          docker build \
            --build-arg ENV_VARIABLES="${{ secrets.ENV_VARIABLES }}" \
            -t ktzkvin/taskmanager:latest .

      - name: Push to Dockerhub
        run: docker push ktzkvin/taskmanager:latest